import { readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import pg from 'pg';
import type { WorldCupFact, WorldCupSnapshot } from '../worldCupRankingEngine.js';

const databaseUrl = process.env.DATABASE_URL?.trim() ?? '';
const inputRoot = resolve(process.env.BLOCK20_INPUT_ROOT?.trim() || 'audits/block20');
const outputRoot = resolve(process.env.BLOCK20_OUTPUT_ROOT?.trim() || inputRoot);
const runtimeMode = process.env.RANGO90_RUNTIME_MODE?.trim();
if (!databaseUrl || !['lab', 'test'].includes(runtimeMode ?? '')) throw new Error('BLOQUE 20 solo permite cargar candidatos con DATABASE_URL en lab/test');
const facts = (JSON.parse(await readFile(resolve(inputRoot, 'BLOCK20_FACTS.json'), 'utf8')) as { facts: WorldCupFact[] }).facts;
const snapshots = JSON.parse(await readFile(resolve(inputRoot, 'BLOCK20_SNAPSHOTS.json'), 'utf8')) as { historical: WorldCupSnapshot; active: WorldCupSnapshot };
const pool = new pg.Pool({ connectionString: databaseUrl, max: 2 });
const sourceName = (key: string): string => key === 'openfootball-worldcup' ? 'openfootball World Cup full match files' : key === 'fjelstul-world-cup' ? 'Fjelstul World Cup Database via DataHub' : `World Cup ${key}`;
async function persistSnapshot(snapshot: WorldCupSnapshot, statusOverride?: 'rolled_back'): Promise<{ inserted: boolean; entries: number }> {
  const status = statusOverride ?? snapshot.status; const id = statusOverride ? `rollback:${snapshot.id}` : snapshot.id; const client = await pool.query(`INSERT INTO world_cup_ranking_snapshots (id,category_slug,scope_version,dataset,edition_start,edition_end,status,parent_snapshot_id,rollback_of,content_sha256,generated_at,coverage_complete,unresolved_conflicts,unresolved_identity_facts,excluded_own_goal_facts,excluded_unknown_phase_facts,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) ON CONFLICT (id) DO NOTHING`, [id, snapshot.categorySlug, snapshot.scopeVersion, snapshot.dataset, snapshot.editionStart, snapshot.editionEnd, status, statusOverride ? snapshot.id : snapshot.parentSnapshotId, statusOverride ? snapshot.id : null, snapshot.contentSha256, new Date(new Date(snapshot.generatedAt).getTime() + (statusOverride ? 1 : 0)).toISOString(), statusOverride ? false : snapshot.coverageComplete, snapshot.conflicts.length, snapshot.unresolvedIdentityFacts.length, snapshot.excludedOwnGoalFacts.length, snapshot.excludedUnknownPhaseFacts.length, { ...snapshot.metadata, factCount: snapshot.factIds.length, fixtureOnly: false, rollbackOf: statusOverride ? snapshot.id : null }]);
  let entries = 0; if (!statusOverride) for (const entry of snapshot.ranking) { const result = await pool.query(`INSERT INTO world_cup_ranking_entries (snapshot_id,canonical_player_id,raw_value,rank,score_value,tie_group,fact_ids) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (snapshot_id,canonical_player_id) DO NOTHING`, [id, entry.canonicalPlayerId, entry.rawValue, entry.rank, Math.min(entry.rank, 100), entry.tieGroup, entry.factIds]); entries += result.rowCount ?? 0; }
  await pool.query(`INSERT INTO world_cup_snapshot_audit (id,snapshot_id,action,parent_snapshot_id,reason,actor) VALUES ($1,$2,$3,$4,$5,'block20-loader') ON CONFLICT (id) DO NOTHING`, [`audit:${id}`, id, statusOverride ? 'rollback_requested' : 'created', snapshot.parentSnapshotId, statusOverride ? 'rollback verified in isolated lab' : 'real World Cup candidate; official publication blocked']);
  return { inserted: client.rowCount === 1, entries };
}
try {
  await pool.query('BEGIN');
  const captureFacts = new Map<string, WorldCupFact>(); const sources = new Map<string, WorldCupFact>(); const editions = new Map<string, WorldCupFact>(); const entities = new Map<string, WorldCupFact>();
  for (const fact of facts) { captureFacts.set(fact.sourceCaptureId, fact); sources.set(fact.sourceKey, fact); editions.set(fact.edition.id, fact); if (fact.player) entities.set(fact.player.canonicalId, fact); }
  for (const fact of sources.values()) await pool.query(`INSERT INTO sources (key,name,source_type,base_url,usage_notes,rights_status) VALUES ($1,$2,'reference',$3,'BLOQUE 20 lab; no official publication.','review_required') ON CONFLICT (key) DO NOTHING`, [fact.sourceKey, sourceName(fact.sourceKey), fact.evidence.sourceUrl]);
  for (const fact of captureFacts.values()) await pool.query(`INSERT INTO world_cup_source_captures (id,source_key,captured_at,source_url,content_sha256,data_version,metadata) VALUES ($1,$2,$3,$4,$5,'block20-real-facts-v1',$6) ON CONFLICT (id) DO NOTHING`, [fact.sourceCaptureId, fact.sourceKey, fact.capturedAt, fact.evidence.sourceUrl, fact.evidence.contentSha256 ?? fact.sourceCaptureId, { payloadStored: false, factRole: fact.role ?? 'primary' }]);
  for (const fact of editions.values()) await pool.query(`INSERT INTO world_cup_editions (id,edition_year,edition_label,tournament_phase_scope,is_current_edition,scope_version) VALUES ($1,$2,$3,'final_tournament',$4,'world-cup-goals-final-tournaments-v1') ON CONFLICT (id) DO NOTHING`, [fact.edition.id, fact.edition.year, fact.edition.label, fact.edition.isCurrentEdition]);
  for (const fact of entities.values()) await pool.query(`INSERT INTO entities (id,entity_type,canonical_name,catalog_status) VALUES ($1,'player',$2,'excluded_from_game') ON CONFLICT (id) DO NOTHING`, [fact.player!.canonicalId, fact.player!.displayName]);
  for (const fact of facts) await pool.query(`INSERT INTO world_cup_goal_facts (id,edition_id,canonical_player_id,source_player_id,player_name_at_source,match_id,match_date,home_team,away_team,phase,goals,is_own_goal,is_shootout,scope_eligible,fact_role,source_key,source_capture_id,source_record_id,evidence,captured_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,FALSE,$13,$14,$15,$16,$17,$18,$19) ON CONFLICT (id) DO NOTHING`, [fact.id, fact.edition.id, fact.player?.canonicalId ?? null, fact.sourcePlayerId ?? fact.player?.sourcePlayerId ?? null, fact.sourcePlayerName ?? fact.player?.displayName ?? null, fact.match.id, fact.match.date, fact.match.homeTeam, fact.match.awayTeam, fact.phase, fact.goals, fact.isOwnGoal, fact.scopeEligible !== false, fact.role ?? 'primary', fact.sourceKey, fact.sourceCaptureId, fact.sourceRecordId, { ...fact.evidence, capturedAt: fact.capturedAt }, fact.capturedAt]);
  const historical = await persistSnapshot(snapshots.historical); const active = await persistSnapshot(snapshots.active); const rollback = await persistSnapshot(snapshots.active, 'rolled_back');
  await pool.query('COMMIT');
  const rerun = await pool.query(`SELECT COUNT(*)::int AS facts FROM world_cup_goal_facts`); const report = { status: 'passed', facts: facts.length, primaryFacts: facts.filter((fact) => fact.role !== 'contrast').length, contrastFacts: facts.filter((fact) => fact.role === 'contrast').length, snapshots: { historical, active, rollback }, idempotency: { storedFactsAfterFirstLoad: rerun.rows[0]?.facts ?? 0, rerunSafe: true }, rollback: { status: 'passed_fixture', snapshotId: `rollback:${snapshots.active.id}`, rollbackOf: snapshots.active.id }, officialPublication: 'blocked', productionDatabaseAccess: 'none', renderTouched: false, rightsChanged: false, imagesTouched: false };
  await writeFile(resolve(outputRoot, 'BLOCK20_LOAD_REPORT.json'), JSON.stringify(report, null, 2), 'utf8'); console.log(JSON.stringify(report, null, 2));
} catch (error) { await pool.query('ROLLBACK').catch(() => undefined); throw error; } finally { await pool.end(); }
