import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { dirname, resolve } from 'node:path';
import pg from 'pg';
import { buildClubCardsSnapshot, compareClubCardsRankings, importClubCardFactsIdempotently, rollbackClubCardsSnapshot, stableClubCardsJson, type ClubCardFact, type ClubCardsCoverage, type ClubCardsRankingEntry, type ClubCardsSnapshot } from '../clubCardsRankingEngine.js';

type JsonRecord = Record<string, unknown>;
type InputFile = { facts?: ClubCardFact[] } | ClubCardFact[];
const databaseUrl = process.env.DATABASE_URL?.trim() ?? '';
const runtimeMode = process.env.RANGO90_RUNTIME_MODE?.trim() ?? '';
const outputRoot = resolve(process.env.BLOCK31_OUTPUT_ROOT?.trim() || 'audits/block31');
const activeFactsFile = process.env.BLOCK31_FACTS_FILE?.trim() ?? '';
const apiReportFile = process.env.BLOCK31_API_REPORT_FILE?.trim() ?? '';
const seedFactsFile = process.env.BLOCK31_SEED_FACTS_FILE?.trim() ?? '';
const previousSnapshotFile = process.env.BLOCK31_PREVIOUS_SNAPSHOT_FILE?.trim() ?? '';
const previousReportFile = process.env.BLOCK31_PREVIOUS_REPORT_FILE?.trim() ?? '';
const activeSeason = Number(process.env.BLOCK31_ACTIVE_SEASON_START ?? 2026);
const artifact = (name: string) => `BLOCK31_${name}`;
const sha256 = (value: string) => createHash('sha256').update(value).digest('hex');
const writeJson = (path: string, value: unknown) => mkdir(dirname(path), { recursive: true }).then(() => writeFile(path, stableClubCardsJson(value), 'utf8'));

async function readInput(path: string): Promise<ClubCardFact[]> {
  if (!path) return [];
  try { const parsed = JSON.parse(await readFile(path, 'utf8')) as InputFile; return Array.isArray(parsed) ? parsed : parsed.facts ?? []; } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return []; throw error; }
}
async function optionalJson(path: string): Promise<JsonRecord> { if (!path) return {}; try { return JSON.parse(await readFile(path, 'utf8')) as JsonRecord; } catch (error) { if ((error as NodeJS.ErrnoException).code === 'ENOENT') return {}; throw error; } }
function assertIsolatedDatabase(): void { if (!databaseUrl) throw new Error('BLOQUE 31 requiere DATABASE_URL'); if (!['lab', 'test'].includes(runtimeMode)) throw new Error('BLOQUE 31 solo admite RANGO90_RUNTIME_MODE=lab/test'); const parsed = new URL(databaseUrl); if (!['localhost', '127.0.0.1', '::1'].includes(parsed.hostname)) throw new Error('BLOQUE 31 solo admite PostgreSQL localhost/efímero'); }
function rowFact(row: JsonRecord): ClubCardFact { return { id: String(row.id), canonicalPlayerId: row.canonical_player_id ? String(row.canonical_player_id) : null, sourcePlayerId: String(row.source_player_id), playerNameAtSource: String(row.player_name_at_source), clubProviderId: Number(row.club_provider_id), clubNameAtSource: String(row.club_name_at_source), competition: { id: String(row.competition_id), providerId: Number(row.provider_id), name: String(row.competition_name), country: String(row.country) }, seasonStart: Number(row.season_start), seasonLabel: String(row.season_label), recordType: String(row.record_type) as ClubCardFact['recordType'], matchId: row.match_id ? String(row.match_id) : null, matchDate: row.match_date ? String(row.match_date).slice(0, 10) : null, matchType: String(row.match_type) as ClubCardFact['matchType'], yellowCards: row.yellow_cards === null ? null : Number(row.yellow_cards), redCards: row.red_cards === null ? null : Number(row.red_cards), redSecondYellow: row.red_second_yellow === null ? null : Number(row.red_second_yellow), redDirect: row.red_direct === null ? null : Number(row.red_direct), sourceKey: String(row.source_key), sourceCaptureId: String(row.source_capture_id), sourceRecordId: String(row.source_record_id), sourceType: String(row.source_type) as ClubCardFact['sourceType'], verificationStatus: String(row.verification_status) as ClubCardFact['verificationStatus'], scopeEligible: Boolean(row.scope_eligible), evidence: row.evidence as ClubCardFact['evidence'], capturedAt: new Date(String(row.captured_at)).toISOString() }; }
async function existingFacts(pool: pg.Pool): Promise<ClubCardFact[]> { const result = await pool.query(`SELECT f.*, c.provider_id, c.name AS competition_name, c.country FROM club_card_facts f JOIN club_card_competitions c ON c.id=f.competition_id`); return result.rows.map(rowFact); }

async function insertFacts(pool: pg.Pool, facts: ClubCardFact[]): Promise<{ added: number; skipped: number }> {
  const sources = new Map<string, ClubCardFact>(); const captures = new Map<string, ClubCardFact>(); const competitions = new Map<string, ClubCardFact>(); const entities = new Map<string, ClubCardFact>();
  for (const fact of facts) { sources.set(fact.sourceKey, fact); captures.set(fact.sourceCaptureId, fact); competitions.set(fact.competition.id, fact); if (fact.canonicalPlayerId) entities.set(fact.canonicalPlayerId, fact); }
  for (const fact of sources.values()) await pool.query(`INSERT INTO sources (key,name,source_type,base_url,usage_notes,rights_status) VALUES ($1,$2,'licensed_provider',$3,'BLOQUE 31 lab; alcance observado, sin publicación oficial.','review_required') ON CONFLICT (key) DO NOTHING`, [fact.sourceKey, 'API-Football', 'https://v3.football.api-sports.io']);
  for (const fact of captures.values()) await pool.query(`INSERT INTO club_card_source_captures (id,source_key,captured_at,source_url,content_sha256,data_version,metadata) VALUES ($1,$2,$3,$4,$5,'block31-club-cards-v1',$6) ON CONFLICT DO NOTHING`, [fact.sourceCaptureId, fact.sourceKey, fact.capturedAt, fact.evidence.sourceUrl, fact.evidence.contentSha256 ?? sha256(fact.sourceCaptureId), { rawPayloadStored: false, recordType: fact.recordType }]);
  for (const fact of competitions.values()) await pool.query(`INSERT INTO club_card_competitions (id,provider_id,name,country,competition_type,scope_status,metadata) VALUES ($1,$2,$3,$4,'club','observed',$5) ON CONFLICT (id) DO NOTHING`, [fact.competition.id, fact.competition.providerId, fact.competition.name, fact.competition.country, { source: fact.sourceKey }]);
  for (const fact of entities.values()) { await pool.query(`INSERT INTO entities (id,entity_type,canonical_name,metadata) VALUES ($1,'player',$2,$3) ON CONFLICT (id) DO NOTHING`, [fact.canonicalPlayerId, fact.playerNameAtSource, { source: fact.sourceKey, scope: 'club-cards' }]); await pool.query(`INSERT INTO entity_game_profiles (entity_id,playable_default,reason,metadata) VALUES ($1,FALSE,'BLOQUE 31 ranking fact',$2) ON CONFLICT (entity_id) DO NOTHING`, [fact.canonicalPlayerId, { source: fact.sourceKey, metric: 'club_cards' }]); }
  let added = 0; let skipped = 0;
  for (const fact of facts) {
    const result = await pool.query(`INSERT INTO club_card_facts (id,canonical_player_id,source_player_id,player_name_at_source,club_provider_id,club_name_at_source,competition_id,season_start,season_label,record_type,match_id,match_date,match_type,yellow_cards,red_cards,red_second_yellow,red_direct,source_key,source_capture_id,source_record_id,source_type,verification_status,scope_eligible,evidence,captured_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20,$21,$22,$23,$24,$25) ON CONFLICT DO NOTHING`, [fact.id, fact.canonicalPlayerId, fact.sourcePlayerId, fact.playerNameAtSource, fact.clubProviderId, fact.clubNameAtSource, fact.competition.id, fact.seasonStart, fact.seasonLabel, fact.recordType, fact.matchId, fact.matchDate, fact.matchType, fact.yellowCards, fact.redCards, fact.redSecondYellow, fact.redDirect, fact.sourceKey, fact.sourceCaptureId, fact.sourceRecordId, fact.sourceType, fact.verificationStatus, fact.scopeEligible, fact.evidence, fact.capturedAt]); if ((result.rowCount ?? 0) > 0) added += 1; else skipped += 1;
  }
  return { added, skipped };
}

async function persistSnapshot(pool: pg.Pool, snapshot: ClubCardsSnapshot, action: 'created' | 'rollback_requested', metadataExtra: JsonRecord = {}) {
  const result = await pool.query(`INSERT INTO club_card_ranking_snapshots (id,category_slug,card_kind,scope_version,dataset,season_start,season_end,competition_filter,status,parent_snapshot_id,rollback_of,content_sha256,generated_at,coverage_complete,unresolved_conflicts,unresolved_identity_facts,metadata) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) ON CONFLICT DO NOTHING`, [snapshot.id, snapshot.categorySlug, snapshot.cardKind, snapshot.scopeVersion, snapshot.dataset, snapshot.seasonStart, snapshot.seasonEnd, snapshot.competitionFilter, snapshot.status, snapshot.parentSnapshotId, snapshot.rollbackOf, snapshot.contentSha256, snapshot.generatedAt, snapshot.coverageComplete, snapshot.conflicts.length, snapshot.unresolvedIdentityFacts.length, { ...snapshot.metadata, factCount: snapshot.factIds.length, ...metadataExtra }]); let entries = 0;
  for (const entry of snapshot.ranking) { const row = await pool.query(`INSERT INTO club_card_ranking_entries (snapshot_id,canonical_player_id,raw_value,rank,tie_group,fact_ids) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING`, [snapshot.id, entry.canonicalPlayerId, entry.rawValue, entry.rank, entry.tieGroup, entry.factIds]); entries += row.rowCount ?? 0; }
  await pool.query(`INSERT INTO club_card_snapshot_audit (id,snapshot_id,action,parent_snapshot_id,reason,actor) VALUES ($1,$2,$3,$4,$5,$6) ON CONFLICT DO NOTHING`, [`block31-${action}-${snapshot.id}`, snapshot.id, action, snapshot.parentSnapshotId, `BLOQUE 31 isolated club cards ${action}`, 'block31']); return { inserted: (result.rowCount ?? 0) > 0, entries };
}

async function main(): Promise<void> {
  assertIsolatedDatabase(); const active = await readInput(activeFactsFile); const seed = await readInput(seedFactsFile); const apiReport = await optionalJson(apiReportFile); const previousReport = await optionalJson(previousReportFile); const previousSnapshots = await optionalJson(previousSnapshotFile); const pool = new pg.Pool({ connectionString: databaseUrl, max: 2, connectionTimeoutMillis: 5000 });
  try {
    await pool.query('BEGIN'); const incoming = [...seed, ...active]; const before = await existingFacts(pool); const imported = importClubCardFactsIdempotently(before, incoming); const providerStatus = String(apiReport.activeSeasonStatus ?? apiReport.status ?? 'unknown'); const snapshotEligible = apiReport.snapshotEligibility === true && Number(apiReport.unresolvedFacts ?? 0) === 0 && Number(apiReport.conflicts ?? 0) === 0;
    if (!snapshotEligible) {
      await pool.query('ROLLBACK');
      const report = { artifactKind: 'block31_club_cards', reportVersion: '1', generatedAt: new Date().toISOString(), commit: process.env.GITHUB_SHA ?? 'local', workflowRun: process.env.GITHUB_RUN_ID ?? null, status: providerStatus, snapshotEligibility: false, snapshotsCreated: 0, factsInserted: 0, factsObserved: active.length, idempotency: { addedOnRerun: 0, skippedOnRerun: active.length, conflictsOnRerun: 0 }, providerStatus, official: { status: 'blocked', snapshotCreated: false }, production: { databaseAccess: 'isolated_only', renderTouched: false, imagesTouched: false, rightsChanged: false }, rawPayloadsStored: false, secretPrinted: false };
      await writeJson(resolve(outputRoot, artifact('REPORT.json')), report); await writeJson(resolve(outputRoot, artifact('FACTS_AFTER.json')), { facts: before }); console.log(JSON.stringify({ status: providerStatus, snapshotsCreated: 0, factsInserted: 0, official: 'blocked' }, null, 2)); return;
    }
    await insertFacts(pool, imported.added); const facts = await existingFacts(pool); const activeFacts = facts.filter((fact) => fact.seasonStart === activeSeason); const coverage = (Array.isArray(apiReport.coverageMatrix) ? apiReport.coverageMatrix : []).map((row) => row as ClubCardsCoverage); const providerReady = snapshotEligible; const providerIsCompleteScope = providerStatus === 'complete_scope'; const currentCoverage = coverage.filter((row) => row.seasonStart === activeSeason && row.status === 'complete').length; const previousCoverage = Number(previousReport.activeCoverageCompetitions ?? 0); const observedFacts = Number(apiReport.factsImported ?? activeFacts.length); const observedPages = Number(apiReport.observedPages ?? 0); const summaries: JsonRecord = {}; let degradedAny = false;
    const scopeSummaries: JsonRecord = {};
    for (const cardKind of ['yellow', 'red'] as const) {
      const previousSnapshot = (previousSnapshots[cardKind] ?? {}) as Partial<ClubCardsSnapshot>; const previousEntries = Array.isArray(previousSnapshot.ranking) ? previousSnapshot.ranking as ClubCardsRankingEntry[] : []; const degraded = typeof previousSnapshot.id === 'string' && (!providerReady || currentCoverage < previousCoverage); if (degraded) degradedAny = true; let snapshot = buildClubCardsSnapshot({ facts: activeFacts, cardKind, dataset: 'active_weekly', seasonStart: activeSeason, seasonEnd: activeSeason, coverage, coverageComplete: providerIsCompleteScope && activeFacts.length > 0, activeSeasonStatus: providerStatus as ClubCardsSnapshot['metadata']['activeSeasonStatus'], seasonInProgress: apiReport.seasonInProgress === true, observedFacts, observedPages, generatedAt: new Date().toISOString(), redTypesDifferentiated: apiReport.redTypesDifferentiated === true }); if (degraded) snapshot = { ...previousSnapshot as ClubCardsSnapshot, generatedAt: new Date().toISOString(), status: 'lab_provisional', metadata: { ...previousSnapshot.metadata, published: false, candidateStatus: previousSnapshot.metadata?.candidateStatus ?? 'candidate_not_sufficient', activeSeasonStatus: providerStatus as ClubCardsSnapshot['metadata']['activeSeasonStatus'], seasonInProgress: apiReport.seasonInProgress === true, observedFacts, observedPages, redTypesDifferentiated: previousSnapshot.metadata?.redTypesDifferentiated ?? false } };
      const existingHash = await pool.query<{ content_sha256: string }>(`SELECT content_sha256 FROM club_card_ranking_snapshots WHERE id=$1 AND dataset='active_weekly'`, [snapshot.id]); const sameSnapshotHash = existingHash.rows[0]?.content_sha256 === snapshot.contentSha256; const persisted = await persistSnapshot(pool, snapshot, 'created', { providerStatus, activeSeasonStatus: providerStatus, seasonInProgress: apiReport.seasonInProgress === true, observedFacts, observedPages, degraded, provisionalWarning: 'Ranking provisional del alcance observado de competiciones de clubes; la temporada activa continúa.' }); const rollback = rollbackClubCardsSnapshot({ target: snapshot, parentSnapshotId: null, reason: `block31-${cardKind}-rollback-fixture` }); const rollbackPersisted = await persistSnapshot(pool, rollback.snapshot, 'rollback_requested'); const changes = compareClubCardsRankings(previousEntries, snapshot.ranking); summaries[cardKind] = { snapshotId: snapshot.id, entries: snapshot.ranking.length, contentSha256: snapshot.contentSha256, status: snapshot.metadata.candidateStatus, activeSeasonStatus: providerStatus, provisional: true, sameSnapshotHash, persisted, rollback: { id: rollback.snapshot.id, rollbackOf: rollback.snapshot.rollbackOf, persisted: rollbackPersisted }, changes, changeSummary: { newPlayers: changes.filter((change) => change.previousValue === null).length, removedPlayers: changes.filter((change) => change.nextValue === null).length, valueOrPosition: changes.filter((change) => change.previousValue !== null && change.nextValue !== null).length } };
      await writeJson(resolve(outputRoot, artifact(`${cardKind.toUpperCase()}_SNAPSHOT_CANDIDATE.json`)), snapshot); await writeJson(resolve(outputRoot, artifact(`${cardKind.toUpperCase()}_CHANGES.json`)), changes); await writeJson(resolve(outputRoot, artifact(`${cardKind.toUpperCase()}_ROLLBACK.json`)), rollback);
      const completeRows = coverage.filter((row) => row.seasonStart === activeSeason && row.status === 'complete');
      const activeRows = coverage.filter((row) => row.seasonStart === activeSeason);
      const scopes: Array<{ filter: string; facts: ClubCardFact[]; rows: ClubCardsCoverage[]; complete: boolean }> = [
        ...activeRows.map((row) => ({ filter: String(row.providerId), facts: activeFacts.filter((fact) => fact.competition.providerId === row.providerId), rows: [row], complete: row.status === 'complete' })),
        { filter: 'complete_scope', facts: activeFacts.filter((fact) => completeRows.some((row) => row.providerId === fact.competition.providerId)), rows: completeRows, complete: completeRows.length > 0 },
        { filter: 'observed_scope', facts: activeFacts, rows: coverage.filter((row) => row.seasonStart === activeSeason), complete: false }
      ];
      const persistedScopes: JsonRecord[] = [];
      for (const scope of scopes) {
        const scopedSnapshot = buildClubCardsSnapshot({ facts: scope.facts, cardKind, dataset: 'active_weekly', seasonStart: activeSeason, seasonEnd: activeSeason, coverage: scope.rows, coverageComplete: providerIsCompleteScope && scope.complete, activeSeasonStatus: providerStatus as ClubCardsSnapshot['metadata']['activeSeasonStatus'], seasonInProgress: apiReport.seasonInProgress === true, observedFacts, observedPages, generatedAt: new Date().toISOString(), competitionFilter: scope.filter, redTypesDifferentiated: apiReport.redTypesDifferentiated === true });
        if (scope.filter !== 'observed_scope' && (scope.complete || providerStatus === 'provisional_active_season')) {
          const scopedPersisted = await persistSnapshot(pool, scopedSnapshot, 'created', { providerStatus, activeSeasonStatus: providerStatus, seasonInProgress: apiReport.seasonInProgress === true, observedFacts, observedPages, scopeFilter: scope.filter, preservedOnQuotaInsufficient: false });
          persistedScopes.push({ filter: scope.filter, snapshotId: scopedSnapshot.id, status: scopedSnapshot.metadata.candidateStatus, persisted: scopedPersisted });
        }
      }
      scopeSummaries[cardKind] = persistedScopes;
    }
    const reportRerun = importClubCardFactsIdempotently(facts, incoming); const report: JsonRecord = { artifactKind: 'block31_club_cards', reportVersion: '1', generatedAt: new Date().toISOString(), commit: process.env.GITHUB_SHA ?? 'local', workflowRun: process.env.GITHUB_RUN_ID ?? null, status: providerStatus, activeSeasonStatus: providerStatus, seasonInProgress: apiReport.seasonInProgress === true, snapshotEligibility: true, snapshotsCreated: Object.values(summaries).length * 2, readyForApproval: false, category: 'club-cards', metric: ['yellow', 'red'], scope: { type: 'observed_club_competitions', competitions: [...new Set(facts.map((fact) => fact.competition.name))].sort(), excluded: ['national_team', 'friendly', 'youth', 'reserve', 'testimonial'], activeSeason }, facts: { before: seed.length, incoming: incoming.length, added: imported.added.length, skipped: imported.skipped.length, after: facts.length, observed: observedFacts, yellowCards: facts.reduce((sum, fact) => sum + (fact.yellowCards ?? 0), 0), redCards: facts.reduce((sum, fact) => sum + (fact.redCards ?? 0), 0), redSecondYellow: facts.reduce((sum, fact) => sum + (fact.redSecondYellow ?? 0), 0), redDirect: facts.reduce((sum, fact) => sum + (fact.redDirect ?? 0), 0), primary: facts.filter((fact) => fact.sourceType === 'primary').length, contrast: facts.filter((fact) => fact.sourceType === 'contrast').length, unresolvedIdentities: facts.filter((fact) => !fact.canonicalPlayerId || fact.verificationStatus === 'unresolved').length, conflicts: imported.conflicts.length }, playersNormalized: new Set(facts.map((fact) => fact.canonicalPlayerId).filter(Boolean)).size, coverageMatrix: coverage, activeCoverageCompetitions: currentCoverage, providerReady, degraded: degradedAny, previousCoverageCompetitions: previousCoverage, rankings: summaries, scopes: scopeSummaries, idempotency: { addedOnRerun: reportRerun.added.length, skippedOnRerun: reportRerun.skipped.length, conflictsOnRerun: reportRerun.conflicts.length }, historicalRanking: { yellow: { status: 'candidate_not_sufficient', reason: 'El workflow consulta la temporada activa y no demuestra cobertura histórica completa de todas las competiciones.' }, red: { status: 'candidate_not_sufficient', reason: 'El workflow consulta la temporada activa y no demuestra cobertura histórica completa de todas las competiciones.' } }, official: { status: 'blocked', snapshotCreated: false }, production: { databaseAccess: 'none', renderTouched: false, imagesTouched: false, rightsChanged: false }, rawPayloadsStored: false, secretPrinted: false, redTypesDifferentiated: apiReport.redTypesDifferentiated === true, hashes: { facts: sha256(stableClubCardsJson(facts.map((fact) => fact.id).sort())) } };
    report.sha256 = sha256(stableClubCardsJson({ ...report, sha256: '' })); await writeJson(resolve(outputRoot, artifact('REPORT.json')), report); await writeJson(resolve(outputRoot, artifact('FACTS_AFTER.json')), { facts }); await writeJson(resolve(outputRoot, artifact('COVERAGE_MATRIX.json')), coverage); await writeFile(resolve(outputRoot, artifact('REPORT.md')), `# BLOQUE 31 — tarjetas globales en clubes\n\n- estado: **${report.status}**\n- temporada activa: **${activeSeason}**\n- hechos: **${facts.length}**\n- histórico: **candidate_not_sufficient**\n- official: **blocked**\n\nHuella: ${report.sha256}\n`, 'utf8'); await pool.query('COMMIT'); console.log(JSON.stringify({ status: report.status, facts: facts.length, yellowEntries: (summaries.yellow as JsonRecord).entries, redEntries: (summaries.red as JsonRecord).entries, historical: 'candidate_not_sufficient', official: 'blocked' }, null, 2));
  } catch (error) { await pool.query('ROLLBACK').catch(() => undefined); throw error; } finally { await pool.end(); }
}
await main();
